routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    
    Route::resource('container', 'ContainerController');
    Route::resource('frieghtForWarder', 'FrieghtForWarderController');
    Route::resource('vessels', 'VesselController');
    Route::resource('agents', 'AgentController');
    Route::resource('import-cargo', 'ImportCargoController');
    Route::post('import-cargo/update-remarks','ImportCargoController@updateRemarks')->name('importCargo.remarks');
    Route::get('importcargo/invoice/{importId}/{status}','ImportCargoController@generateImportPdf')->name('importCargo.invoice');
    
    Route::resource('export-cargo', 'ExportCargoController');
    Route::post('export-cargo/update-remarks','ExportCargoController@updateRemarks')->name('exportCargo.remarks');

    // Route::post('export-cargo/show-certificate-of-measurement','ExportCargoController@showCertificateOfMeasurement')->name('exportCargo.showCertificateOfMeasurement');
    Route::get('export-cargo/show-certificate-of-measurement/{id}','ExportCargoController@showCertificateOfMeasurement')->name('exportCargo.showCertificateOfMeasurement');

    Route::post('export-cargo/add-certificate-of-measurement','ExportCargoController@AddCertificateOfMeasurement')->name('exportCargo.AddCertificateOfMeasurement');
    
    Route::post('AjaxCallForExportCargoToGetAgent','ExportCargoJsonController@AjaxCallForExportCargoToGetAgent')->name('AjaxCallForExportCargoToGetAgent'); // Add by Bilal 17Feb2021
    Route::post('AjaxCallForExportCargoToGetVessel','ExportCargoJsonController@AjaxCallForExportCargoToGetVessel')->name('AjaxCallForExportCargoToGetVessel'); // Add by Bilal 17Feb2021
    Route::post('AjaxCallForExportCargoToGetConsignee','ExportCargoJsonController@AjaxCallForExportCargoToGetConsignee')->name('AjaxCallForExportCargoToGetConsignee'); // Add by Bilal 17Feb2021
    Route::post('AjaxCallForExportCargoToGetContainer','ExportCargoJsonController@AjaxCallForExportCargoToGetContainer')->name('AjaxCallForExportCargoToGetContainer'); // Add by Bilal 19Feb2021
    
    Route::get('exportcargo/invoice/{id}','ExportCargoController@generateExportPdf')->name('exportCargo.invoice');
    Route::get('exportcargoDetail/invoice/{id}','ExportCargoController@generateExportDetailPdf')->name('exportcargoDetail.invoice');

    
    
    Route::post('exportdetial-delete','ExportCargoJsonController@AjaxCallForExportDetailSoftDelete')->name('exportdetial-delete');
    
    Route::get('container-exist/{containerName?}','ImportCargoJsonController@containerExist')->name('container-exist');
    Route::get('vessel-fetch/{search?}','ImportCargoJsonController@vesselFetch')->name('vessel-fetch');
    Route::get('container-fetch/{search?}','ImportCargoJsonController@containerFetch')->name('container-fetch');
    Route::post('importdetal-delete','ImportCargoJsonController@deleteImportCargoDetail')->name('importdetal-delete');
    Route::resource('itemtypes', 'ItemTypeController');
    Route::resource('users', 'UserController', [
        'only' => ['index', 'create', 'store','edit','update','destroy']
    ]);

    Route::post('changePassword', 'changePasswordController@ChangePassword')->name('changePassword');

    Route::get('report','HomeController@ViewReport')->name('report.view');
    Route::post('generateExportReportUsingVesselAndContainerAndVoyage','ExportCargoController@generateExportReportUsingVesselAndContainerAndVoyage')->name('report.export');

    Route::post('generateImportPackageReportUsingVesselAndContainerAndVoyage','ImportCargoController@generateImportPackageReportUsingVesselAndContainerAndVoyage')->name('report.import_package');

    Route::post('generateImportVehicleReportUsingVesselAndContainerAndVoyage','ImportCargoController@generateImportVehicleReportUsingVesselAndContainerAndVoyage')->name('report.import_vehicle');

    Route::post('report/ref','HomeController@storeReport')->name('report.ref');


    Route::get('ViewReport','HomeController@viewDetailsReport')->name('report.ViewReport');

    Route::post('ViewReport/delete','ReportController@ref_report_delete')->name('report.delete');


});

Route::get("sendEmail", "EmailController@sendEmailToUser");

app/Models/Vessel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Vessel extends Model
{
    public $fillable = ['name'];
    public $timestamps = false;

    public function importcargoes()
    {
        return $this->hasMany('App\Models\ImportCargo','vesselId', 'id');
    }

    public function exportcargoes()
    {
        return $this->hasMany('App\Models\ExportCargo','vesselId', 'id');
    }
}

app/Http/Controllers/VesselController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Vessel;
class VesselController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vessels = Vessel::all();
        return view('vessels.index',compact('vessels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vessels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $agent = new Vessel;
        $agent->name = strtolower($request->name);
        $agent->save();
        return redirect()->route('vessels.index')->with('success','Vessel added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vessel = Vessel::find($id);
        return view('vessels.edit',compact('vessel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $agent = Vessel::findOrFail($id);
        $agent->name = strtolower($request->name);
        $agent->save();
        return redirect()->route('vessels.index')->with('success','Vessel updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Vessel::findOrFail($id)->delete();
        return redirect()->route('vessels.index');
    }
}

resources/views/vessels/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption font-red-sunglo">
                        <i class="icon-settings font-red-sunglo"></i>
                        <span class="caption-subject bold uppercase">Add New Vessel</span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form role="form" method="POST" action="{{route('vessels.store')}}">
                        @csrf
                        <div class="form-body">
                            <div class="form-group @error('name') has-error @enderror ">
                                <label>Vessel Name</label>
                                <input type="text" name="name" class="form-control" placeholder="Vessel Name">
                                @error('name')
                                <span class="text-sm text-danger" style="padding: 5px;font-size:12px">{{$message}}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Save</button>
                            <a href="{{route('vessels.index')}}" class="btn default">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vessels/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption font-red-sunglo">
                        <i class="icon-settings font-red-sunglo"></i>
                        <span class="caption-subject bold uppercase"> Edit Vessel</span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form role="form" method="POST" action="{{route('vessels.update',$vessel->id)}}">
                        @method('PUT')
                        @csrf
                        <div class="form-body">
                            <div class="form-group @error('name') has-error @enderror">
                                <label>Agent Name</label>
                                <input type="text" name="name" class="form-control" value="{{old('name') != null ?old('name'):$vessel->name}}" placeholder="Vessel Name">
                                @error('name')
                                <span class="text-sm text-danger" style="padding: 5px;font-size:12px">{{$message}}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Update</button>
                            <a href="{{route('vessels.index')}}" class="btn default">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vessels/index.blade.php
@extends('layouts.app')
@section('customCSS')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->

    <style>
        a.dt-button.buttons-print.btn.dark.btn-outline {
            display: none;
        }

        .btn-outline {
            display: none;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">View All Vessels</span>
                    </div>
                    {{-- <div class="tools"> </div> --}}
                    <a href="{{route('vessels.create')}}" class="btn btn-danger pull-right">Add Vessel</a>
                </div>

                @if (session('success'))
                    <div id="prefix_1128615150407" class="custom-alerts alert alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                        <i class="fa-lg fa fa-warning"></i>  
                        {{session('success')}}
                    </div>
                @endif

                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_table">
                        <thead>
                            <tr>
                                <th>Sr.No</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $a =0;
                            @endphp
                            @foreach ($vessels as $key => $item)
                                <tr>
                                    <td>{{++$a}}</td>
                                    <td>{{$item->name}}</td>
                                    <td>
                                        
                                        <form action="{{route('vessels.destroy',$item->id)}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <a href="{{route('vessels.edit',$item->id)}}" class="btn btn-primary">Edit</a>
                                            @if (count($item->exportcargoes) == 0 && count($item->importcargoes) == 0)
                                                <button type="submit" class="btn btn-danger delete-btn">Delete</button>
                                            @endif

                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection
@section('customJS')
    <script src="{{asset('assets/global/scripts/datatable.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{asset('assets/pages/scripts/table-datatables-buttons.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        $(document).ready(function(){
            $('#sample_table').dataTable();
        })

        $('.delete-btn').click(function (e) { 
            e.preventDefault();
            
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this record!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
                })
                .then((willDelete) => {
                if (willDelete) {
                    $(this).closest('form').submit();
                } else {
                    swal("Your record is safe!");
                }
            });
        });
    </script>
@endsection