routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    
    Route::resource('container', 'ContainerController');
    Route::resource('frieghtForWarder', 'FrieghtForWarderController');
    Route::resource('vessels', 'VesselController');
    Route::resource('agents', 'AgentController');
    Route::resource('import-cargo', 'ImportCargoController');
    Route::post('import-cargo/update-remarks','ImportCargoController@updateRemarks')->name('importCargo.remarks');
    Route::get('importcargo/invoice/{importId}/{status}','ImportCargoController@generateImportPdf')->name('importCargo.invoice');
    
    Route::resource('export-cargo', 'ExportCargoController');
    Route::post('export-cargo/update-remarks','ExportCargoController@updateRemarks')->name('exportCargo.remarks');

    // Route::post('export-cargo/show-certificate-of-measurement','ExportCargoController@showCertificateOfMeasurement')->name('exportCargo.showCertificateOfMeasurement');
    Route::get('export-cargo/show-certificate-of-measurement/{id}','ExportCargoController@showCertificateOfMeasurement')->name('exportCargo.showCertificateOfMeasurement');

    Route::post('export-cargo/add-certificate-of-measurement','ExportCargoController@AddCertificateOfMeasurement')->name('exportCargo.AddCertificateOfMeasurement');
    
    Route::post('AjaxCallForExportCargoToGetAgent','ExportCargoJsonController@AjaxCallForExportCargoToGetAgent')->name('AjaxCallForExportCargoToGetAgent'); // Add by Bilal 17Feb2021
    Route::post('AjaxCallForExportCargoToGetVessel','ExportCargoJsonController@AjaxCallForExportCargoToGetVessel')->name('AjaxCallForExportCargoToGetVessel'); // Add by Bilal 17Feb2021
    Route::post('AjaxCallForExportCargoToGetConsignee','ExportCargoJsonController@AjaxCallForExportCargoToGetConsignee')->name('AjaxCallForExportCargoToGetConsignee'); // Add by Bilal 17Feb2021
    Route::post('AjaxCallForExportCargoToGetContainer','ExportCargoJsonController@AjaxCallForExportCargoToGetContainer')->name('AjaxCallForExportCargoToGetContainer'); // Add by Bilal 19Feb2021
    
    Route::get('exportcargo/invoice/{id}','ExportCargoController@generateExportPdf')->name('exportCargo.invoice');
    Route::get('exportcargoDetail/invoice/{id}','ExportCargoController@generateExportDetailPdf')->name('exportcargoDetail.invoice');

    
    
    Route::post('exportdetial-delete','ExportCargoJsonController@AjaxCallForExportDetailSoftDelete')->name('exportdetial-delete');
    
    Route::get('container-exist/{containerName?}','ImportCargoJsonController@containerExist')->name('container-exist');
    Route::get('vessel-fetch/{search?}','ImportCargoJsonController@vesselFetch')->name('vessel-fetch');
    Route::get('container-fetch/{search?}','ImportCargoJsonController@containerFetch')->name('container-fetch');
    Route::post('importdetal-delete','ImportCargoJsonController@deleteImportCargoDetail')->name('importdetal-delete');
    Route::resource('itemtypes', 'ItemTypeController');
    Route::resource('users', 'UserController', [
        'only' => ['index', 'create', 'store','edit','update','destroy']
    ]);

    Route::post('changePassword', 'changePasswordController@ChangePassword')->name('changePassword');

    Route::get('report','HomeController@ViewReport')->name('report.view');
    Route::post('generateExportReportUsingVesselAndContainerAndVoyage','ExportCargoController@generateExportReportUsingVesselAndContainerAndVoyage')->name('report.export');

    Route::post('generateImportPackageReportUsingVesselAndContainerAndVoyage','ImportCargoController@generateImportPackageReportUsingVesselAndContainerAndVoyage')->name('report.import_package');

    Route::post('generateImportVehicleReportUsingVesselAndContainerAndVoyage','ImportCargoController@generateImportVehicleReportUsingVesselAndContainerAndVoyage')->name('report.import_vehicle');

    Route::post('report/ref','HomeController@storeReport')->name('report.ref');


    Route::get('ViewReport','HomeController@viewDetailsReport')->name('report.ViewReport');

    Route::post('ViewReport/delete','ReportController@ref_report_delete')->name('report.delete');


});

Route::get("sendEmail", "EmailController@sendEmailToUser");

resources/views/importcargoes/index.blade.php
@extends('layouts.app')
@section('customCSS')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css">
    <!-- END PAGE LEVEL PLUGINS -->

    <style>
        a.dt-button.buttons-print.btn.dark.btn-outline {
            display: none;
        }

        .btn-outline {
            display: none;
        }

        table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child, table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child::before{
            display: none;
        }
        table.dataTable.dtr-inline.collapsed>tbody>tr>td, table.dataTable>thead>tr>th , table.dataTable>tfoot>tr>th  {
            display: table-cell !important;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">View All Import Cargos</span>
                    </div>
                    <div class="tools"> </div>
                    <a href="{{route('import-cargo.create')}}" class="btn btn-danger" style="float:right">Add Import Cargo</a>
                </div>
                {{-- <a href="{{route('import-cargo.create')}}" class="btn btn-danger">Add Import Cargo</a> --}}
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_table">
                        <thead>
                            <tr>
                                <th>Sr.No</th>
                                <th>Added By</th>
                                <th>Serial No</th>
                                <th>Voy</th>
                                <th>OF</th>
                                <th>Date of Measurement</th>
                                <th>Container</th>
                                <th>Vessel</th>
                                <th>Status</th>
                                <th style="min-width: 210px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $a =0;
                            @endphp
                            @foreach ($importcargos as $key => $item)
                                <tr>
                                    <td>{{++$a}}</td>
                                    <td>{{$item->user->name}}</td>
                                    <td>{{$item->serialNo}}</td>
                                    <td>{{$item->voy}}</td>
                                    <td>{{date_format(date_create($item->departureDate),"j M, Y")}}</td>
                                    <td>{{date_format(date_create($item->dom_des),"j M, Y")}}</td>
                                    <td>{{$item->container->name}}</td>
                                    <td>{{$item->vessel->name}}</td>
                                    <td>{{$item->status}}</td>
                                    <td>
                                        <a href="{{route('import-cargo.show',$item->id)}}" class="btn btn-info"><i class="fa fa-eye"></i></a>
                                        <a href="{{route('import-cargo.edit',$item->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                        <a href="{{route('importCargo.invoice',['importId'=>$item->id,'status'=>45])}}" class="btn btn-danger">45 <i class="fa fa-print"></i></a>
                                        @if ($item->status == 23)
                                        <a href="{{route('importCargo.invoice',['importId'=>$item->id,'status'=>23])}}" class="btn btn-danger">23 <i class="fa fa-print"></i></a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection
@section('customJS')
    <script src="{{asset('assets/global/scripts/datatable.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
        $(document).ready(function(){
            $('#sample_table').dataTable();
            @if (Session::has("message")) 
            toastr['success']("{{Session::get('message')}}", "Success Message")
            @endif
        })
    </script>
@endsection

resources/views/importcargoes/invoice-form23.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widtd=device-widtd, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        @page { margin: 10px; }
        body { margin: 10px; }
        *{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 0.95em;
        }
        table.first-detail
        {
            width: 100%;
            border-collapse: collapse;
            border: none;
            margin: 10px 0px;
        }
        table.first-detail td
        {
            padding: 5px;
        }
        table.details
        {
            width: 100%;
            border-collapse: collapse;
            border: 1px black solid;
            margin-bottom: 20px
        }
        table.details td
        {
            padding: 5px;
            border: 1px black solid;
        }
        .text-center
        {
            text-align: center;
            
        }
        .h1-size{
            font-size: 1.5em;
        }
        .text-underline{
            text-decoration: underline;
        }
        .img-logo
        {
            width: 150px;
            height: auto;
            position: absolute;
        }
        .form-no
        {
            position: absolute;
            right: 10px;
        }
        .text-span-size
        {
            font-size: 1.1em;
        }
    </style>
</head>
<body>
    <img src="{{ public_path("images/unitedlogo.png") }}" class="img-logo">
    <p class="form-no"><b>Form No: 23</b></p>
    <h1 class="text-center h1-size">UNITED MARINE SURVEYORS (PVT) LTD.</h1>
    <p class="text-center">MARINE, FIRE AND MOTOR SURVEYORS, CERTIFIED IICL CONTAINER INSPECTORS, LIQUID<br>BULK & DRY CARGO INSPECTORS, NAUITICAL & ENGINEERING CONSULTANTS.</p>
    <p class="text-center">------------------------------------ (AN ISO 9001 : 2015 CERTIFIED COMPANY)--------------------------------------</p>
    <p class="text-center">Suite # 207, Shaheen Centre, Schon Circle, Kehkashan Block 7, Clifton, Karachi - 75600, Pakistan.<br>Tele: (92-21) 3586 1355-56 Fax: (92-21) 3586 1358 Email:info@ums.com.pk Web:http://www.ums.com.pk</p>
    <h2 class="text-underline text-center">DAILY MEASURMENT FOR IMPORT CARGO</h2>
    <table class="details">
        <tbody>
            <tr>
                <td><b>M.V.</b> <span class="text-underline text-span-size">{{$imports->vessel->name}}</span></td>
                <td><b>VOY</b> <span class="text-underline text-span-size">{{$imports->voy}}</span></td>
                <td><b>OF</b> <span class="text-underline text-span-size">{{date("d-M-Y",strtotime($imports->departureDate))}}</span></td>
            </tr>
            <tr>
                <td colspan="2"><b>DATE OF MEASURMENT/DE-STUFFING</b> <span class="text-underline text-span-size">{{date("d-M-Y",strtotime($imports->dom_des))}}</span></td>
                <td><b>CONTAINER NO.</b> <span class="text-underline text-span-size">{{$imports->container->name}}</span></td>
            </tr>
        </tbody>
    </table>
    <table class="details">
        <thead>
            <tr>
                <th>S.No</th>
                <th>INDEX #</th>
                <th>STOWAGE ON BOARD</th>
                <th>MARKS & NOS</th>
                <th>DESCRIPTION OF CARGO</th>
                <th>CONTAINER NO</th>
                <th>SIZE</th>
                <th>TYPE</th>
                <th>SEAL NO</th>
                <th>REMARKS</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($imports->importcargosdetail as $key => $item)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$item->cargo_index}}</td>
                    <td>{{$item->stowageOnBoard}}</td>
                    <td>{{$item->mark_no}}</td>
                    <td>{{$item->description}}</td>
                    <td>{{$imports->container->name}}</td>
                    <td>{{$item->size}}</td>
                    <td>{{$item->itemTypeId}}</td>
                    <td>{{$item->sealNo}}</td>
                    <td>{{$item->remarks}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>

resources/views/importcargoes/invoice-form45.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widtd=device-widtd, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        @page { margin: 10px; }
        body { margin: 10px; }
        *{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 0.95em;
        }
        table.first-detail
        {
            width: 100%;
            border-collapse: collapse;
            border: none;
            margin: 10px 0px;
        }
        table.first-detail td
        {
            padding: 5px;
        }
        table.details
        {
            width: 100%;
            border-collapse: collapse;
            border: 1px black solid;
            margin-bottom: 20px
        }
        table.details td
        {
            padding: 5px;
            border: 1px black solid;
        }
        .text-center
        {
            text-align: center;
            
        }
        .h1-size{
            font-size: 1.5em;
        }
        .text-underline{
            text-decoration: underline;
        }
        .img-logo
        {
            width: 60px;
            height: auto;
            position: absolute;
        }
        .form-no
        {
            position: absolute;
            right: 10px;
        }
        .text-span-size
        {
            font-size: 1.1em;
        }
    </style>
</head>
<body>
    <img src="{{ public_path("images/unitedlogo.png") }}" class="img-logo">
    <p class="form-no"><b>Form No: 45</b></p>
    <h1 class="text-center h1-size">UNITED MARINE SURVEYORS (PVT) LTD.</h1>
    <p class="text-center">MARINE, FIRE AND MOTOR SURVEYORS, CERTIFIED IICL CONTAINER INSPECTORS, LIQUID<br>BULK & DRY CARGO INSPECTORS, NAUITICAL & ENGINEERING CONSULTANTS.</p>
    <p class="text-center">------------------------------------ (AN ISO 9001 : 2015 CERTIFIED COMPANY)--------------------------------------</p>
    <p class="text-center">Suite # 207, Shaheen Centre, Schon Circle, Kehkashan Block 7, Clifton, Karachi - 75600, Pakistan.<br>Tele: (92-21) 3586 1355-56 Fax: (92-21) 3586 1358 Email:info@ums.com.pk Web:http://www.ums.com.pk</p>
    <h2 class="text-underline text-center">DAILY MEASURMENT FOR IMPORT CARGO</h2>
    <table class="details">
        <tbody>
            <tr>
                <td><b>M.V.</b> <span class="text-underline text-span-size">{{$imports->vessel->name}}</span></td>
                <td><b>VOY</b> <span class="text-underline text-span-size">{{$imports->voy}}</span></td>
                <td><b>OF</b> <span class="text-underline text-span-size">{{date("d-M-Y",strtotime($imports->departureDate))}}</span></td>
            </tr>
            <tr>
                <td colspan="2"><b>DATE OF MEASURMENT/DE-STUFFING</b> <span class="text-underline text-span-size">{{date("d-M-Y",strtotime($imports->dom_des))}}</span></td>
                <td><b>CONTAINER NO.</b> <span class="text-underline text-span-size">{{$imports->container->name}}</span></td>
            </tr>
        </tbody>
    </table>
    <table class="details">
        <thead>
            <tr>
                <th>S.No</th>
                <th>INDEX #</th>
                <th>MARKS & NUMBER</th>
                <th>DESCRIPTION</th>
                <th>MEASURMENT M3</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($imports->importcargosdetail as $key => $item)
            <tr>
                <td>{{++$key}}</td>
                <td>{{$item->cargo_index}}</td>
                <td>{{$item->mark_no}}</td>
                <td>{{$item->description}}</td>
                <td>{{$item->measurment_m3}}</td>
            </tr>
            @endforeach
            
        </tbody>
    </table>
</body>
</html>

resources/views/importcargoes/show.blade.php
@extends('layouts.app')
@section('customCSS')
<link href="{{asset('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css">
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption font-red-sunglo">
                        <i class="icon-settings font-red-sunglo"></i>
                        <span class="caption-subject bold uppercase">View Import Cargo</span>
                    </div>
                    <button class="btn btn-primary pull-right" id="btn-toggle-remarks" data-value="hide">Show Remarks</button>
                </div>
                <div class="portlet-body">
                        <div class="form-body row">
                            <div class="col-sm-12">
                                @if (Session::has('message'))
                                    <div class="note note-success">
                                        <h5>{{Session::get('message')}}</h5>
                                    </div>
                                @endif
                                <table class="table table-striped table-bordered" style="margin-top:20px">
                                    <thead>
                                        <tr>
                                            <th>M.V</th>
                                            <th>VOY</th>
                                            <th>OF</th>
                                            <th>Date of Measurement/De-Stuffing</th>
                                            <th>Container</th>
                                            <th>Size</th>
                                            <th>Type</th>
                                            <th>Status</th>
                                            <th>Serial No</th>
                                            <th>IGM Number</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{$importcargo->vessel->name}}</td>
                                            <td>{{$importcargo->voy}}</td>
                                            <td>{{date_format(date_create($importcargo->departureDate),"j M, Y")}}</td>
                                            <td>{{date_format(date_create($importcargo->dom_des),"j M, Y")}}</td>
                                            <td>{{$importcargo->container->name}}</td>
                                            <td>{{$importcargo->container->size}}</td>
                                            <td>{{$importcargo->container->ContainerType->name}}</td>
                                            <td>{{$importcargo->status}}</td>
                                            <td>{{$importcargo->serialNo}}</td>
                                            <td>{{$importcargo->igm_number}}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="col-sm-12">
                                <h4>Import Cargo Details</h4>
                            </div>
                            <div class="col-sm-12">
                                <form action="{{route('importCargo.remarks')}}" method="post" id="formRemarks">
                                    <input type="hidden" name="importcargoId" value="{{Request::segment(2)}}">
                                    @csrf
                                    <table class="table table-striped table-bordered" style="margin-top:20px" id="importDetailTable">
                                        <thead>
                                            <tr>
                                                <th>Index</th>
                                                <th>Stowage on Board</th>
                                                <th>Marks & NOS</th>
                                                <th>Description</th>
                                                {{-- <th>Size</th>
                                                <th>Type</th> --}}
                                                <th>Seal No</th>
                                                <th class="remarks-colum hidden">Remarks</th>
                                                <th class="remarks-colum hidden">Accessories Found At De-Stuffing</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($importcargo->importcargosdetail as $item)
                                                <tr>
                                                    <td>{{@$item->cargo_index}}</td>
                                                    <td>{{@$item->stowageOnBoard}}</td>
                                                    <td>{{@$item->mark_no}}</td>
                                                    <td>{{@$item->description}}</td>
                                                    {{-- <td>{{@$item->size}}</td>
                                                    <td>{{@$item->itemTypeId}}</td> --}}
                                                    <td>{{@$item->sealNo}}</td>
                                                    <td class="remarks-colum hidden">
                                                        <input type="hidden" name="importdetailId[]" value="{{@$item->id}}">
                                                        <input type="text" value="{{@$item->remarks}}" name="remarks[]" class="form-control" placeholder="Enter Remarks" />
                                                    </td>
                                                    <td class="remarks-colum hidden">
                                                        <input type="text" value="{{@$item->accessories}}" name="accessories[]" class="form-control" id="">
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" form="formRemarks" class="btn blue hidden updateRemarksBtn">Update Remarks</button>
                            <a href="{{route('import-cargo.index')}}" class="btn default">Cancel</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('customJS')
    <script>
        $(document).on('click','#btn-toggle-remarks',function(){
            if($(this).attr('data-value') === 'hide')
            {
                $('.remarks-colum').removeClass('hidden');
                $(this).attr('data-value','show');
                $(this).text('Hide Remarks');
                $('.updateRemarksBtn').removeClass('hidden');
            }
            else
            {
                $('.remarks-colum').addClass('hidden');
                $(this).attr('data-value','hide');
                $(this).text('Show Remarks');
                $('.updateRemarksBtn').addClass('hidden');
            }
        })
    </script>
@endsection